# Site Settings
lang: en
title: Fabric Catalyst
tagline: Fabric Catalyst
email: lesanta@microsoft.com
description: >
  This is a collection of resources designed to accelerate partner adoption and foster innovation through Microsoft Fabri.
baseurl: "/fabriccatalyst"
url: "https://microsoft.github.io/fabriccatalyst/"
permalink: pretty
theme: bulma-clean-theme

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true

markdown: kramdown
highlighter: rouge

include:
  - img
  - docs
  - assets

social:
  x: https://x.com/msFabricconf
  youtube: https://www.youtube.com/@MicrosoftFabric
  linkedin: https://www.linkedin.com/showcase/microsoftfabric/posts/?feedView=all
